import type { ChecklistTemplate } from './types';

/**
 * Built-in car rental operational checklists.
 */
export const CHECKLISTS: ChecklistTemplate[] = [
  {
    id: 'vehicle-pickup',
    title: 'Vehicle Pickup Checklist',
    description: 'Complete this checklist before releasing a vehicle to the customer.',
    items: [
      { id: 'vp-1', label: 'Customer driving licence verified (held ≥1 year)', required: true },
      {
        id: 'vp-2',
        label: 'Passport or national ID checked and matches booking name',
        required: true,
      },
      { id: 'vp-3', label: "Credit card in renter's name presented for deposit", required: true },
      { id: 'vp-4', label: 'Age requirement met (21+ standard, 25+ premium)', required: true },
      { id: 'vp-5', label: 'All documents scanned into Kinsen system', required: true },
      { id: 'vp-6', label: 'Rental agreement reviewed and signed by customer', required: true },
      { id: 'vp-7', label: 'Insurance package confirmed and explained', required: true },
      {
        id: 'vp-8',
        label: 'Walk-around inspection completed with customer present',
        required: true,
      },
      {
        id: 'vp-9',
        label: 'All 4 sides + roof + interior photographed (Kinsen app)',
        required: true,
      },
      { id: 'vp-10', label: 'Fuel gauge photographed (full tank / ≥80% EV)', required: true },
      { id: 'vp-11', label: 'Odometer reading recorded', required: true },
      { id: 'vp-12', label: 'Deposit hold authorized on credit card', required: true },
      { id: 'vp-13', label: 'Additional drivers added to contract (if any)', required: false },
      {
        id: 'vp-14',
        label: 'Child seat installed and demonstrated (if requested)',
        required: false,
      },
      { id: 'vp-15', label: 'GPS / WiFi / accessories provided (if requested)', required: false },
      { id: 'vp-16', label: 'Cross-border permission documented (if applicable)', required: false },
      {
        id: 'vp-17',
        label: 'Emergency contact info and accident form location explained',
        required: true,
      },
      { id: 'vp-18', label: 'Keys and all documents handed to customer', required: true },
    ],
  },
  {
    id: 'vehicle-return',
    title: 'Vehicle Return Checklist',
    description: 'Complete this checklist when a customer returns a vehicle.',
    items: [
      { id: 'vr-1', label: 'Vehicle received and parked in return bay', required: true },
      { id: 'vr-2', label: 'Odometer reading recorded and compared to pickup', required: true },
      { id: 'vr-3', label: 'Fuel gauge checked and photographed', required: true },
      { id: 'vr-4', label: 'Exterior walk-around inspection completed', required: true },
      { id: 'vr-5', label: 'All 4 sides + roof photographed', required: true },
      { id: 'vr-6', label: 'Interior condition inspected and photographed', required: true },
      { id: 'vr-7', label: 'Comparison with pickup photos — new damage noted?', required: true },
      {
        id: 'vr-8',
        label: 'If new damage: customer shown damage and acknowledgment obtained',
        required: false,
        helpText: 'Only if new damage found',
      },
      {
        id: 'vr-9',
        label: 'If new damage: Damage Report Form (DRF) filled within 1 hour',
        required: false,
        helpText: 'Send to damage@kinsen-rentals.com',
      },
      {
        id: 'vr-10',
        label: 'All accessories returned (GPS, WiFi, child seat, etc.)',
        required: true,
      },
      { id: 'vr-11', label: 'Keys collected', required: true },
      {
        id: 'vr-12',
        label: 'Final charges calculated (fuel, mileage, late fee, cleaning)',
        required: true,
      },
      { id: 'vr-13', label: 'Return receipt provided to customer', required: true },
      { id: 'vr-14', label: 'Deposit hold release initiated', required: true },
      {
        id: 'vr-15',
        label: 'Vehicle status updated in system (returned/needs cleaning/needs repair)',
        required: true,
      },
    ],
  },
  {
    id: 'accident-response',
    title: 'Accident Response Checklist',
    description: 'Steps to follow when a customer reports an accident or collision.',
    items: [
      {
        id: 'ar-1',
        label: 'Confirmed safety of all parties (injuries? Call 112 if yes)',
        required: true,
      },
      {
        id: 'ar-2',
        label: 'Customer has completed European Accident Statement form',
        required: true,
        helpText: 'Located in glove compartment',
      },
      {
        id: 'ar-3',
        label: 'Photos taken: all damage, license plates, surroundings, other vehicle',
        required: true,
      },
      {
        id: 'ar-4',
        label: 'Police report filed (if required by law or injuries involved)',
        required: false,
      },
      { id: 'ar-5', label: 'Customer reminded: DO NOT admit fault or negotiate', required: true },
      { id: 'ar-6', label: 'Kinsen Emergency Line called: +30-210-555-0199', required: true },
      {
        id: 'ar-7',
        label: 'Towing arranged via AutoHelp GR (if vehicle undriveable)',
        required: false,
      },
      {
        id: 'ar-8',
        label: 'Replacement vehicle dispatched (if available)',
        required: false,
        helpText: 'Within 90 min in metro areas',
      },
      { id: 'ar-9', label: 'All accident documents collected from customer', required: true },
      { id: 'ar-10', label: 'Insurance claim opened within 24 hours', required: true },
      { id: 'ar-11', label: 'Ops Dashboard updated: incident record created', required: true },
      { id: 'ar-12', label: 'Branch Manager notified', required: true },
    ],
  },
  {
    id: 'shift-handoff',
    title: 'Shift Handoff Checklist',
    description: 'Ensure smooth handoff to the next shift.',
    items: [
      { id: 'sh-1', label: 'All pending returns noted with expected times', required: true },
      { id: 'sh-2', label: 'Overdue vehicles flagged and status noted', required: true },
      { id: 'sh-3', label: 'Upcoming pickups for next 4 hours listed', required: true },
      { id: 'sh-4', label: 'Open damage reports summarized', required: true },
      { id: 'sh-5', label: 'Cash drawer counted and reconciled', required: true },
      { id: 'sh-6', label: 'Unresolved customer issues noted', required: false },
      { id: 'sh-7', label: 'Vehicle prep status checked (cleaned, fueled, ready)', required: true },
      { id: 'sh-8', label: 'Shift notes written in Ops Dashboard', required: true },
    ],
  },
  {
    id: 'daily-opening',
    title: 'Daily Branch Opening Checklist',
    description: 'Steps for opening the branch at the start of the day.',
    items: [
      { id: 'do-1', label: 'Branch alarm deactivated and doors opened', required: true },
      { id: 'do-2', label: 'IT systems powered on and operational', required: true },
      { id: 'do-3', label: 'Kinsen system logged in and synced', required: true },
      { id: 'do-4', label: "Today's reservations reviewed (pickups + returns)", required: true },
      { id: 'do-5', label: 'Fleet status checked — all vehicles accounted for', required: true },
      {
        id: 'do-6',
        label: "Vehicles for today's pickups confirmed clean and fueled",
        required: true,
      },
      { id: 'do-7', label: 'Key cabinet checked — all keys in correct slots', required: true },
      { id: 'do-8', label: "Previous shift's notes reviewed", required: true },
      { id: 'do-9', label: 'Cash drawer set up with correct float', required: true },
      {
        id: 'do-10',
        label: 'Branch exterior: signage visible, parking lot clear',
        required: false,
      },
    ],
  },
];
