// Default feature flags for Kinsen Chat
import type { FeatureFlag } from './types';

export const DEFAULT_FLAGS: FeatureFlag[] = [
  {
    id: 'openai',
    name: 'OpenAI Integration',
    description: 'Use OpenAI-compatible API for chat responses instead of template engine',
    enabled: false,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'voice-input',
    name: 'Voice Input',
    description: 'Enable Web Speech API voice input in chat',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    description: 'Allow users to toggle dark mode',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'macros',
    name: 'Macros & Calculators',
    description: 'Show macro/calculator panel in chat',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'checklists',
    name: 'Operational Checklists',
    description: 'Show checklist panel in chat',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'workflows',
    name: 'Guided Workflows',
    description: 'Enable multi-step guided workflows',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'vehicle-board',
    name: 'Vehicle Status Board',
    description: 'Show fleet status board page',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'customer-lookup',
    name: 'Customer Lookup',
    description: 'Enable customer/booking search in sidebar',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'email-generator',
    name: 'Email Generator',
    description: 'Generate customer emails from chat context',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'escalations',
    name: 'Escalation System',
    description: 'Allow agents to escalate conversations to supervisors',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'notifications',
    name: 'Notification Center',
    description: 'Show notification bell with alerts',
    enabled: true,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'offline-mode',
    name: 'Offline Mode',
    description: 'Cache knowledge notes locally for offline use',
    enabled: false,
    updatedAt: '',
    updatedBy: 'system',
  },
  {
    id: 'i18n',
    name: 'Multi-Language',
    description: 'Enable Greek language option',
    enabled: false,
    updatedAt: '',
    updatedBy: 'system',
  },
];
