// Workflow templates for car rental operations

import type { WorkflowTemplate } from './types';

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'damage-claim',
    title: 'Damage Claim Processing',
    description: 'Step-by-step workflow for processing a vehicle damage claim from discovery to resolution.',
    category: 'operations',
    initialStepId: 'assess',
    steps: [
      {
        id: 'assess',
        title: 'Initial Damage Assessment',
        description: 'Document the damage found on the vehicle.',
        type: 'input',
        fields: [
          { name: 'rentalId', label: 'Rental/Booking ID', type: 'text', required: true },
          { name: 'vehiclePlate', label: 'Vehicle Plate', type: 'text', required: true },
          { name: 'damageLocation', label: 'Damage Location', type: 'select', options: ['Front Bumper', 'Rear Bumper', 'Left Side', 'Right Side', 'Hood', 'Roof', 'Interior', 'Windshield', 'Wheels/Tires', 'Undercarriage'], required: true },
          { name: 'damageType', label: 'Damage Type', type: 'select', options: ['Scratch', 'Dent', 'Crack', 'Broken Part', 'Stain/Burn', 'Missing Part', 'Mechanical'], required: true },
          { name: 'description', label: 'Detailed Description', type: 'textarea', required: true },
        ],
        nextStepId: 'photos',
      },
      {
        id: 'photos',
        title: 'Photo Documentation',
        description: 'Take and document photos of the damage.',
        type: 'checklist',
        checklistItems: [
          'Take wide shot showing full vehicle with damage visible',
          'Take close-up of damage area',
          'Take photo of vehicle plate number',
          'Take photo of mileage/odometer',
          'Compare with pickup photos if available',
          'Note any pre-existing damage from pickup checklist',
        ],
        nextStepId: 'insurance-check',
      },
      {
        id: 'insurance-check',
        title: 'Insurance Coverage Check',
        description: 'Determine what insurance the customer has.',
        type: 'choice',
        choices: [
          { label: 'Full Coverage (€0 deductible) — Covered fully', nextStepId: 'notify-covered' },
          { label: 'Medium Coverage (€600 deductible) — Partial', nextStepId: 'estimate' },
          { label: 'Basic Coverage (€1,200 deductible) — Partial', nextStepId: 'estimate' },
          { label: 'No Insurance — Customer pays all', nextStepId: 'estimate' },
        ],
      },
      {
        id: 'notify-covered',
        title: 'Fully Covered — Notify Customer',
        description: 'Damage is covered under full insurance. Inform the customer and close.',
        type: 'info',
        nextStepId: 'complete',
      },
      {
        id: 'estimate',
        title: 'Cost Estimate',
        description: 'Get or enter the repair cost estimate.',
        type: 'input',
        fields: [
          { name: 'estimatedCost', label: 'Estimated Repair Cost (€)', type: 'number', required: true },
          { name: 'deductible', label: 'Customer Deductible (€)', type: 'number', required: true },
          { name: 'customerCharge', label: 'Amount Customer Owes (€)', type: 'number', required: true },
        ],
        nextStepId: 'approval-needed',
      },
      {
        id: 'approval-needed',
        title: 'Manager Approval Required?',
        description: 'Does this charge need manager approval?',
        type: 'choice',
        choices: [
          { label: 'Charge ≤ €500 — No approval needed', nextStepId: 'notify-customer' },
          { label: 'Charge > €500 — Needs manager approval', nextStepId: 'manager-approval' },
          { label: 'Customer disputes — Needs manager review', nextStepId: 'manager-approval' },
        ],
      },
      {
        id: 'manager-approval',
        title: 'Await Manager Approval',
        description: 'Submit for manager approval. This step will create an escalation.',
        type: 'info',
        nextStepId: 'notify-customer',
      },
      {
        id: 'notify-customer',
        title: 'Notify Customer',
        description: 'Send damage notification to the customer.',
        type: 'checklist',
        checklistItems: [
          'Generate damage notification email using macro',
          'Include all photos as attachments',
          'Include cost breakdown',
          'Send via email and/or SMS',
          'Record communication in system',
        ],
        nextStepId: 'complete',
      },
      {
        id: 'complete',
        title: 'Claim Complete',
        description: 'Damage claim has been processed and documented.',
        type: 'info',
      },
    ],
  },
  {
    id: 'new-rental-walkthrough',
    title: 'New Rental Setup',
    description: 'Complete walkthrough for setting up a new rental from reservation to key handoff.',
    category: 'operations',
    initialStepId: 'verify-booking',
    steps: [
      {
        id: 'verify-booking',
        title: 'Verify Booking Details',
        description: 'Confirm the reservation and customer details.',
        type: 'input',
        fields: [
          { name: 'bookingId', label: 'Booking ID', type: 'text', required: true },
          { name: 'customerName', label: 'Customer Name', type: 'text', required: true },
          { name: 'vehicleClass', label: 'Reserved Vehicle Class', type: 'select', options: ['Economy', 'Compact', 'Midsize', 'SUV', 'Premium', 'Luxury', 'Convertible', 'Van'], required: true },
        ],
        nextStepId: 'customer-docs',
      },
      {
        id: 'customer-docs',
        title: 'Customer Document Verification',
        description: 'Check all required documents.',
        type: 'checklist',
        checklistItems: [
          'Valid driver\'s license (check expiry)',
          'Second form of ID (passport/national ID)',
          'Credit card in driver\'s name',
          'Minimum age requirement met (21+, or 25+ for luxury)',
          'International Driving Permit if non-EU license',
          'Additional driver documents if applicable',
        ],
        nextStepId: 'insurance-select',
      },
      {
        id: 'insurance-select',
        title: 'Insurance Selection',
        description: 'Help customer choose insurance package.',
        type: 'choice',
        choices: [
          { label: 'Full Coverage (€0 deductible) — €15/day extra', nextStepId: 'extras' },
          { label: 'Medium Coverage (€600 deductible) — €8/day extra', nextStepId: 'extras' },
          { label: 'Basic Coverage (€1,200 deductible) — Included', nextStepId: 'extras' },
        ],
      },
      {
        id: 'extras',
        title: 'Extras & Add-ons',
        description: 'Offer available extras.',
        type: 'checklist',
        checklistItems: [
          'GPS Navigation (€5/day)',
          'Child Seat (€5/day)',
          'Booster Seat (€3/day)',
          'Additional Driver (€7/day)',
          'Roadside Assistance Plus (€4/day)',
          'One-way drop-off (if applicable, €30-80)',
          'Cross-border permit (if applicable, €20/trip)',
        ],
        nextStepId: 'vehicle-assign',
      },
      {
        id: 'vehicle-assign',
        title: 'Vehicle Assignment',
        description: 'Select and prepare the vehicle.',
        type: 'input',
        fields: [
          { name: 'vehicleId', label: 'Assigned Vehicle ID', type: 'text', required: true },
          { name: 'vehiclePlate', label: 'License Plate', type: 'text', required: true },
          { name: 'mileage', label: 'Current Mileage (km)', type: 'number', required: true },
          { name: 'fuelLevel', label: 'Fuel Level (%)', type: 'number', required: true },
        ],
        nextStepId: 'walkaround',
      },
      {
        id: 'walkaround',
        title: 'Vehicle Walk-Around',
        description: 'Complete pre-rental vehicle inspection.',
        type: 'checklist',
        checklistItems: [
          'Note all existing scratches/dents on diagram',
          'Take 4-corner photos (front, rear, left, right)',
          'Check tire condition and pressure',
          'Verify spare tire and jack present',
          'Check all lights (headlights, brake, indicators)',
          'Verify fuel level matches recorded level',
          'Check interior condition (seats, dashboard, mats)',
          'Confirm GPS/extras are installed',
        ],
        nextStepId: 'handoff',
      },
      {
        id: 'handoff',
        title: 'Key Handoff & Briefing',
        description: 'Final briefing and key handover.',
        type: 'checklist',
        checklistItems: [
          'Customer signs rental agreement',
          'Deposit pre-authorization charged on credit card',
          'Explain fuel policy (return same level)',
          'Explain return time and late fee policy',
          'Provide emergency contact number',
          'Show vehicle controls (fuel type, parking brake)',
          'Hand over keys and documents',
          'Wish safe travels!',
        ],
      },
    ],
  },
  {
    id: 'refund-process',
    title: 'Refund Processing',
    description: 'Step-by-step workflow for processing customer refunds with appropriate approvals.',
    category: 'finance',
    initialStepId: 'refund-details',
    steps: [
      {
        id: 'refund-details',
        title: 'Refund Request Details',
        description: 'Enter the refund request information.',
        type: 'input',
        fields: [
          { name: 'bookingId', label: 'Booking ID', type: 'text', required: true },
          { name: 'customerName', label: 'Customer Name', type: 'text', required: true },
          { name: 'refundAmount', label: 'Refund Amount (€)', type: 'number', required: true },
          { name: 'reason', label: 'Reason', type: 'select', options: ['Overcharge', 'Cancellation', 'Service Issue', 'Vehicle Downgrade', 'Insurance Claim', 'Goodwill Gesture', 'Other'], required: true },
          { name: 'description', label: 'Detailed Reason', type: 'textarea', required: true },
        ],
        nextStepId: 'refund-approval',
      },
      {
        id: 'refund-approval',
        title: 'Approval Level',
        description: 'Determine required approval level based on amount.',
        type: 'choice',
        choices: [
          { label: 'Under €50 — Agent can approve', nextStepId: 'process-refund' },
          { label: '€50 - €200 — Supervisor approval needed', nextStepId: 'await-approval' },
          { label: 'Over €200 — Manager approval needed', nextStepId: 'await-approval' },
        ],
      },
      {
        id: 'await-approval',
        title: 'Await Approval',
        description: 'Escalate for approval. This will create a notification for the approver.',
        type: 'info',
        nextStepId: 'process-refund',
      },
      {
        id: 'process-refund',
        title: 'Process Refund',
        description: 'Execute the refund transaction.',
        type: 'checklist',
        checklistItems: [
          'Verify original payment method on file',
          'Process refund through payment system',
          'Record refund reference number',
          'Update booking record with refund note',
          'Send refund confirmation email to customer',
        ],
      },
    ],
  },
  {
    id: 'complaint-handling',
    title: 'Customer Complaint Handling',
    description: 'Structured approach to handling and resolving customer complaints.',
    category: 'customer-service',
    initialStepId: 'log-complaint',
    steps: [
      {
        id: 'log-complaint',
        title: 'Log Complaint',
        description: 'Record the complaint details.',
        type: 'input',
        fields: [
          { name: 'customerName', label: 'Customer Name', type: 'text', required: true },
          { name: 'bookingId', label: 'Booking ID (if applicable)', type: 'text', required: false },
          { name: 'category', label: 'Complaint Category', type: 'select', options: ['Vehicle Quality', 'Service Quality', 'Billing Dispute', 'Wait Time', 'Staff Behavior', 'Safety Concern', 'Booking Error', 'Other'], required: true },
          { name: 'description', label: 'Complaint Description', type: 'textarea', required: true },
          { name: 'severity', label: 'Severity', type: 'select', options: ['Low — Minor inconvenience', 'Medium — Service failure', 'High — Safety or major issue'], required: true },
        ],
        nextStepId: 'severity-route',
      },
      {
        id: 'severity-route',
        title: 'Resolution Path',
        description: 'Choose resolution path based on severity.',
        type: 'choice',
        choices: [
          { label: 'Low — Resolve immediately with apology', nextStepId: 'resolve' },
          { label: 'Medium — Offer compensation + resolve', nextStepId: 'compensate' },
          { label: 'High — Escalate to manager immediately', nextStepId: 'escalate-complaint' },
        ],
      },
      {
        id: 'compensate',
        title: 'Offer Compensation',
        description: 'Select appropriate compensation.',
        type: 'choice',
        choices: [
          { label: 'Free day added to rental', nextStepId: 'resolve' },
          { label: 'Vehicle upgrade', nextStepId: 'resolve' },
          { label: '10% discount on current rental', nextStepId: 'resolve' },
          { label: 'Free extras (GPS, child seat, etc.)', nextStepId: 'resolve' },
          { label: 'Loyalty points bonus', nextStepId: 'resolve' },
        ],
      },
      {
        id: 'escalate-complaint',
        title: 'Escalate to Manager',
        description: 'This complaint requires immediate manager attention. An escalation will be created.',
        type: 'info',
        nextStepId: 'resolve',
      },
      {
        id: 'resolve',
        title: 'Resolution & Follow-up',
        description: 'Document the resolution.',
        type: 'checklist',
        checklistItems: [
          'Apologize sincerely to customer',
          'Explain resolution/compensation offered',
          'Customer acknowledges resolution',
          'Document resolution in system',
          'Send follow-up email within 24 hours',
          'Flag for satisfaction survey',
        ],
      },
    ],
  },
];
